Skip the variable event with 0 length
The UEFI firmware measures the Secure Boot variables such as PK, KEK,
db, and dbx, etc. even when those variables are empty. An empty UEFI
variable basically means it doesn't exist, so those variables won't
exist in efivarfs, and this causes the error like this:

Error: Unable to read EFI variable "PK-8be4df61-93ca-11d2-aa0d-00e098032b8c"
Error: Failed to re-hash event 4 type EFI_VARIABLE_DRIVER_CONFIG

This commit ignores the file reading error when the variable length is
0 so that we can continue for the further actions like sealing.

Signed-off-by: Gary Lin <glin@suse.com>